import React, { useEffect, useRef } from "react";
import { X } from "lucide-react";

export function AccessibleDialog({ className = "", role = "dialog", title, subtitle, titleId, descriptionId, busy, onClose, children }: { className?: string; role?: "dialog" | "alertdialog"; title: string; subtitle: string; titleId: string; descriptionId?: string; busy: boolean; onClose: () => void; children: React.ReactNode }) {
  const dialogRef = useRef<HTMLDivElement>(null), previousFocus = useRef<HTMLElement | null>(null), closeRef = useRef(onClose), busyRef = useRef(busy);
  closeRef.current = onClose; busyRef.current = busy;
  useEffect(() => { previousFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; const frame = requestAnimationFrame(() => { const root = dialogRef.current; (root?.querySelector<HTMLElement>("[data-autofocus]:not(:disabled)") || root?.querySelector<HTMLElement>("button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex='-1'])"))?.focus(); }); return () => { cancelAnimationFrame(frame); previousFocus.current?.focus(); }; }, []);
  const keyDown = (event: React.KeyboardEvent) => { if (event.key === "Escape" && !busyRef.current) { event.preventDefault(); closeRef.current(); return; } if (event.key !== "Tab") return; const items = Array.from(dialogRef.current?.querySelectorAll<HTMLElement>("button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex='-1'])") || []); if (!items.length) { event.preventDefault(); return; } const found = items.indexOf(document.activeElement as HTMLElement), current = found >= 0 ? found : event.shiftKey ? 0 : -1, next = (current + (event.shiftKey ? -1 : 1) + items.length) % items.length; event.preventDefault(); items[next]?.focus(); };
  return <div className="modal-backdrop"><div ref={dialogRef} className={`modal ${className}`} role={role} aria-modal="true" aria-labelledby={titleId} aria-describedby={descriptionId} onKeyDown={keyDown}><div className="modal-head"><div><h2 id={titleId}>{title}</h2><p id={descriptionId}>{subtitle}</p></div><button type="button" className="icon-btn" title="关闭" aria-label="关闭" disabled={busy} onClick={onClose}><X size={16}/></button></div>{children}</div></div>;
}
