import { useEffect, useMemo, useRef, useState } from "react";
import { Bot, ChevronDown, CircleStop, Code2, FileCode2, Maximize2, RefreshCw, ShieldCheck, Terminal, TriangleAlert } from "lucide-react";
import { api } from "./api.js";
import { isTerminalRun, mergeRunEvents, type StageRun, type StageRunEvent } from "./run-observability.js";
import { buildStreamEntries, type StreamEntry } from "./stream-view.js";

export function InlineRunStream({initialRun,onOpenDetails,onTerminal}:{initialRun:StageRun;onOpenDetails:()=>void;onTerminal:()=>Promise<void>}){
  const [run,setRun]=useState(initialRun),[events,setEvents]=useState<StageRunEvent[]>(initialRun.events||[]),[connection,setConnection]=useState("正在连接"),[follow,setFollow]=useState(true),[now,setNow]=useState(Date.now());
  const viewport=useRef<HTMLDivElement>(null),terminalSent=useRef(false);
  const entries=useMemo(()=>buildStreamEntries(events),[events]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{let source:EventSource|undefined,closed=false;terminalSent.current=false;api<StageRun>(`/runs/${initialRun.id}`).then(snapshot=>{if(closed)return;setRun(snapshot);setEvents(snapshot.events||[]);if(isTerminalRun(snapshot.status)){setConnection("已结束");return}const after=(snapshot.events||[]).at(-1)?.sequence||0;source=new EventSource(`/api/runs/${snapshot.id}/events?after=${after}`);source.onopen=()=>setConnection("实时连接正常");source.addEventListener("run-event",message=>{const event=JSON.parse((message as MessageEvent).data);setEvents(current=>mergeRunEvents(current,[event]));if(["run.completed","run.failed","run.interrupted"].includes(event.type)){source?.close();setConnection("已结束");api<StageRun>(`/runs/${snapshot.id}`).then(setRun);if(!terminalSent.current){terminalSent.current=true;onTerminal().catch(()=>{})}}});source.onerror=()=>setConnection("连接中断，正在重连")}).catch(()=>setConnection("无法读取执行快照"));return()=>{closed=true;source?.close()}},[initialRun.id]);
  useEffect(()=>{if(follow&&viewport.current)viewport.current.scrollTop=viewport.current.scrollHeight},[entries,follow]);
  const elapsed=Math.max(0,Math.floor((now-new Date(run.createdAt).getTime())/1000));
  const onScroll=()=>{const node=viewport.current;if(!node)return;setFollow(node.scrollHeight-node.scrollTop-node.clientHeight<48)};
  return <div className="inline-run-stream"><div className="stream-head"><div><span className="eyebrow">AI 实时执行</span><h3><RefreshCw className={isTerminalRun(run.status)?"":"spin"} size={16}/>{isTerminalRun(run.status)?"执行已结束":"正在处理"}</h3></div><div className="stream-actions"><button className="secondary" disabled title="当前执行器暂不支持主动停止"><CircleStop size={16}/>停止</button><button className="secondary" onClick={onOpenDetails}><Maximize2 size={16}/>完整详情</button></div></div><div className="stream-meta"><span>模型 <b>{run.model||"-"}</b></span><span>已运行 <b>{formatElapsed(elapsed)}</b></span><span>事件 <b>{events.length}</b></span><span className={connection.includes("中断")?"disconnected":""}>{connection}</span></div><div className="stream-viewport" ref={viewport} onScroll={onScroll} aria-live="polite">{entries.length?entries.map(item=><StreamCard item={item} key={item.id}/>):<div className="stream-wait"><Bot size={24}/><span>等待第一个可见事件</span></div>}</div>{!follow&&<button className="stream-latest" onClick={()=>setFollow(true)}><ChevronDown size={15}/>回到最新</button>}<div className="stream-foot"><span>仅展示模型输出、工具操作和结果</span><span>最后事件 #{events.at(-1)?.sequence||0}</span></div></div>;
}

function StreamCard({item}:{item:StreamEntry}){const icon=item.kind==="command"?<Terminal/>:item.kind==="file"?<FileCode2/>:item.kind==="gate"?<ShieldCheck/>:item.kind==="diagnostic"||item.state==="failed"?<TriangleAlert/>:item.kind==="message"?<Bot/>:<Code2/>;const body=item.kind==="command"||item.kind==="diagnostic"?<details open={item.state==="running"}><summary>查看输出</summary><pre>{item.text||"没有输出"}</pre></details>:<p>{item.text}</p>;return <article className={`stream-entry ${item.kind} ${item.state||""}`}><div className="stream-entry-icon">{icon}</div><div><header><b>{item.title}</b><time>{item.createdAt?new Date(item.createdAt).toLocaleTimeString():`#${item.sequence}`}</time></header>{body}</div></article>}
function formatElapsed(seconds:number){const minutes=Math.floor(seconds/60),rest=seconds%60;return minutes?`${minutes}分${rest}秒`:`${rest}秒`}
