import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { AlertTriangle, Bot, Check, ChevronRight, CircleDot, ClipboardCheck, Code2, FileText, FolderGit2, LayoutDashboard, ListTodo, PanelLeftClose, PanelLeftOpen, Play, Plus, RefreshCw, Settings, ShieldCheck, TestTube2, X } from "lucide-react";
import { returnStage, stageLabels, statusLabels, workflowStages, type GateConfig, type Requirement, type WorkflowStage, type WorkflowStatus } from "@ai-workflow/shared";
import { api, patch, post } from "./api.js";
import { groupRequirements } from "./dashboard.js";
import "./styles.css";
import "./associations.css";
import "./execution.css";
import "./run-observability.css";
import { displayRunEvents, eventLabel as runEventLabel, isTerminalRun, latestRunForStage, mergeRunEvents, type StageRun } from "./run-observability.js";
import { gateLabel, gateReasons, latestGateForStage } from "./gate-view.js";
import { groupReworkItems } from "./rework-view.js";
import { humanOverrideView } from "./human-override-view.js";
import { integrationView } from "./integration-view.js";
import { InlineRunStream } from "./inline-run-stream.js";
import { productArtifactView } from "./product-artifact-view.js";
import { projectKnowledgeView } from "./project-knowledge-view.js";
import { filterRequirements, navigationTarget, type QueueFilter } from "./navigation-view.js";

type Detail = Requirement & { projectId?: string; projectName?: string; version?: number; clarifications?: string; artifacts: any[]; approvals: any[]; executions?: any[]; revisions?: any[]; runs?: StageRun[]; codingEvidence?: any; reworkContext?: any; humanOverride?: any; integrationRun?: any;knowledgeChanges?:any };
type Page = "dashboard" | "requirements" | "projects" | "settings";

function App() {
  const [items, setItems] = useState<Requirement[]>([]);
  const [selected, setSelected] = useState<Detail | null>(null);
  const [page, setPage] = useState<Page>("dashboard");
  const [modal, setModal] = useState<"new" | "edit" | "run" | "approve" | "human_override" | "integrate" | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [runView, setRunView] = useState<StageRun | null>(null);
  const [queueFilter,setQueueFilter]=useState<QueueFilter|null>(null);
  const [sidebarCollapsed,setSidebarCollapsed]=useState(()=>localStorage.getItem("flowgate.sidebarCollapsed")==="1");
  const queues = useMemo(() => groupRequirements(items), [items]);
  const visibleItems=useMemo(()=>filterRequirements(items,queueFilter),[items,queueFilter]);
  const refresh = async () => { const data = await api<Requirement[]>("/requirements"); setItems(data); if (selected) setSelected(await api(`/requirements/${selected.id}`)); };
  useEffect(() => { refresh().catch((e) => setError(e.message)); }, []);
  const open = async (item: Requirement) => { setSelected(await api(`/requirements/${item.id}`)); setPage("requirements"); };
  const navigate=(next:Page,filter:QueueFilter|null=null)=>{const target=navigationTarget(next,filter);setPage(target.page);setSelected(null);setQueueFilter(target.queueFilter)};
  const selectQueue=(filter:QueueFilter)=>navigate("requirements",filter);
  const toggleSidebar=()=>setSidebarCollapsed(value=>{const next=!value;localStorage.setItem("flowgate.sidebarCollapsed",next?"1":"0");return next});

  return <div className={sidebarCollapsed?"app-shell sidebar-collapsed":"app-shell"}>
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><CircleDot size={20}/></div><div><strong>Flowgate</strong><small>AI 研发工作台</small></div><button className="sidebar-toggle" onClick={toggleSidebar} aria-label={sidebarCollapsed?"展开左侧菜单":"收起左侧菜单"} title={sidebarCollapsed?"展开左侧菜单":"收起左侧菜单"}>{sidebarCollapsed?<PanelLeftOpen size={17}/>:<PanelLeftClose size={17}/>}</button></div>
      <nav>
        <Nav icon={<LayoutDashboard/>} label="工作台" active={page === "dashboard"&&!selected} onClick={() => navigate("dashboard")}/>
        <Nav icon={<ListTodo/>} label="需求" active={page === "requirements"&&!selected} onClick={() => navigate("requirements")}/>
        <Nav icon={<FolderGit2/>} label="项目" active={page === "projects"} onClick={() => navigate("projects")}/>
      </nav>
      <div className="queue-nav"><span>我的工作</span>
        <Queue label="待人工审批" count={queues.approvals.length} active={queueFilter==="approvals"} onClick={()=>selectQueue("approvals")}/><Queue label="AI 待启动" count={queues.ready.length} active={queueFilter==="ready"} onClick={()=>selectQueue("ready")}/><Queue label="AI 执行中" count={queues.running.length} active={queueFilter==="running"} onClick={()=>selectQueue("running")}/><Queue label="已阻塞" count={queues.blocked.length} active={queueFilter==="blocked"} onClick={()=>selectQueue("blocked")}/>
      </div>
      <button className="nav-bottom" title="设置" onClick={() => navigate("settings")}><Settings size={17}/><span>设置</span></button>
    </aside>
    <main>
      <header><div><h1>{selected ? selected.title : pageTitle(page)}</h1><p>{selected ? `${selected.code} · ${stageLabels[selected.stage]}` : pageSubtitle(page)}</p></div>
        <button className="primary" onClick={() => setModal("new")}><Plus size={17}/>新建需求</button></header>
      {error && <div className="alert"><AlertTriangle size={18}/>{error}<button onClick={() => setError("")}><X size={16}/></button></div>}
      {selected ? <RequirementDetail item={selected} onRun={() => setModal("run")} onViewRun={setRunView} onEdit={() => setModal("edit")} onApprove={() => setModal("approve")} onHumanOverride={() => setModal("human_override")} onIntegrate={() => setModal("integrate")} onRefresh={refresh} onProjectChanged={async()=>setSelected(await api(`/requirements/${selected.id}`))}/> :
       page === "projects" ? <Projects/> : page === "settings" ? <SettingsPage/> : <Dashboard items={visibleItems} queues={queues} queueFilter={queueFilter} onQueue={selectQueue} onClearFilter={()=>setQueueFilter(null)} onOpen={open}/>}
    </main>
    {modal === "new" && <NewRequirement onClose={() => setModal(null)} onDone={async () => { setModal(null); await refresh(); }}/>}
    {modal === "edit" && selected && <EditRequirement item={selected} onClose={() => setModal(null)} onDone={async () => { setModal(null); await refresh(); }}/>}
    {modal === "run" && selected && <RunModal item={selected} busy={busy} onClose={() => setModal(null)} onRun={async () => { setBusy(true); setError(""); try { const run=await post<StageRun>(`/requirements/${selected.id}/run`, { context: "使用当前已批准材料" }); setModal(null); setRunView(run); await refresh(); } catch(e:any){ setError(e.message); setModal(null); await refresh(); } finally { setBusy(false); } }}/>}
    {modal === "approve" && selected && <ApprovalModal item={selected} onClose={() => setModal(null)} onSubmit={async (body: Record<string, unknown>) => { await post(`/requirements/${selected.id}/approve`, body); setModal(null); await refresh(); }}/>}
    {modal === "human_override" && selected && <HumanOverrideModal item={selected} onClose={() => setModal(null)} onSubmit={async (comment:string) => { await post(`/requirements/${selected.id}/human-override`, {comment}); setModal(null); await refresh(); }}/>}
    {modal === "integrate" && selected && <IntegrationConfirm item={selected} busy={busy} onClose={()=>setModal(null)} onSubmit={async(protectedBranchConfirmation:string)=>{setBusy(true);try{await post(`/requirements/${selected.id}/integrate`,{protectedBranchConfirmation});setModal(null);await refresh()}catch(e:any){setError(e.message);setModal(null)}finally{setBusy(false)}}}/>}
    {runView && <RunDetailsModal initialRun={runView} onClose={() => setRunView(null)} onTerminal={refresh}/>}
  </div>;
}

function Nav({icon,label,active,onClick}:any){return <button className={active?"nav active":"nav"} title={label} aria-label={label} onClick={onClick}>{React.cloneElement(icon,{size:18})}<span>{label}</span></button>}
function Queue({label,count,active,onClick}:{label:string,count:number,active:boolean,onClick:()=>void}){return <button className={active?"queue active":"queue"} onClick={onClick}><span>{label}</span><b>{count}</b></button>}

function Dashboard({items,queues,queueFilter,onQueue,onClearFilter,onOpen}:any){const filterLabels:any={approvals:"待人工审批",ready:"AI 待启动",running:"AI 执行中",blocked:"已阻塞"};return <div className="content"><section className="stats">
  <Stat label="待人工审批" value={queues.approvals.length} tone="amber" icon={<ClipboardCheck/>} active={queueFilter==="approvals"} onClick={()=>onQueue("approvals")}/><Stat label="AI 待启动" value={queues.ready.length} tone="green" icon={<Bot/>} active={queueFilter==="ready"} onClick={()=>onQueue("ready")}/><Stat label="执行中" value={queues.running.length} tone="blue" icon={<RefreshCw/>} active={queueFilter==="running"} onClick={()=>onQueue("running")}/><Stat label="已阻塞" value={queues.blocked.length} tone="red" icon={<AlertTriangle/>} active={queueFilter==="blocked"} onClick={()=>onQueue("blocked")}/>
  </section><section className="section"><div className="section-head"><div><h2>{queueFilter?filterLabels[queueFilter]:"近期需求"}</h2><p>{queueFilter?`筛选结果 ${items.length} 条`:"按更新时间查看当前工作流"}</p></div>{queueFilter&&<button className="secondary" onClick={onClearFilter}>清除筛选</button>}</div>
  <div className="table"><div className="table-row table-header"><span>需求</span><span>当前阶段</span><span>状态</span><span>优先级</span><span></span></div>
  {items.length ? items.map((r:Requirement)=><button className="table-row" key={r.id} onClick={()=>onOpen(r)}><span><b>{r.title}</b><small>{r.code}</small></span><span>{stageLabels[r.stage]}</span><span><Status status={r.status}/></span><span>{priority(r.priority)}</span><ChevronRight size={17}/></button>) : <Empty/>}</div></section></div>}
function Stat({label,value,tone,icon,active,onClick}:any){return <button className={active?"stat active":"stat"} onClick={onClick}><div className={`stat-icon ${tone}`}>{React.cloneElement(icon,{size:19})}</div><div><strong>{value}</strong><span>{label}</span></div></button>}
function Status({status}:{status:WorkflowStatus}){return <span className={`status ${status}`}>{statusLabels[status]}</span>}
function Empty(){return <div className="empty"><FileText size={30}/><b>还没有需求</b><span>从新建需求开始第一条 AI 工作流</span></div>}

function RequirementDetail({item,onRun,onViewRun,onEdit,onApprove,onHumanOverride,onIntegrate,onRefresh,onProjectChanged}:{item:Detail,onRun:()=>void,onViewRun:(run:StageRun)=>void,onEdit:()=>void,onApprove:()=>void,onHumanOverride:()=>void,onIntegrate:()=>void,onRefresh:()=>Promise<void>,onProjectChanged:()=>void}){const [viewStage,setViewStage]=useState<WorkflowStage>(item.stage);useEffect(()=>setViewStage(item.stage),[item.id,item.stage]);const latest=item.artifacts.find((artifact:any)=>artifact.stage===viewStage);const stageRun=latestRunForStage(item.runs,viewStage);const gate=latestGateForStage(item.approvals,viewStage);const overrideApproval=item.approvals.find((approval:any)=>approval.stage===viewStage&&approval.actor_type==="human_override");const overrideView=humanOverrideView(item.stage,item.humanOverride);const needsRequirementCorrection=item.status==="returned"&&item.stage==="intake";const isRework=item.status==="returned"&&item.stage!=="intake";const isCurrentView=viewStage===item.stage;return <div className="content detail">
  <div className="timeline">{workflowStages.map((s,i)=><button type="button" onClick={()=>setViewStage(s)} className={`step ${s===item.stage?"current":workflowStages.indexOf(item.stage)>i?"done":""} ${s===viewStage?"selected":""}`} key={s}><span>{workflowStages.indexOf(item.stage)>i?<Check size={14}/>:i+1}</span><small>{stageLabels[s]}</small></button>)}</div>
  <div className="detail-grid"><section className="section"><div className="section-head"><div><h2>{stageLabels[viewStage]}</h2><p>当前需求版本 v{item.version||1} · {isCurrentView?"当前阶段成果与人工门禁":"历史阶段产物"}</p></div>{isCurrentView&&item.status==="ai_running"&&stageRun?<button className="run-status-button" onClick={()=>onViewRun(stageRun)} title="查看 AI 执行详情"><Status status={item.status}/></button>:isCurrentView?<Status status={item.status}/>:<span className="status">历史</span>}</div>
    {viewStage==="integration"?<IntegrationPanel item={item} current={isCurrentView} onIntegrate={onIntegrate} onRefresh={onRefresh}/>:isCurrentView&&item.status==="ai_running"&&stageRun?<InlineRunStream initialRun={stageRun} onOpenDetails={()=>onViewRun(stageRun)} onTerminal={onRefresh}/>:<>{isCurrentView&&item.reworkContext?.targetStage===viewStage&&<ReworkPanel context={item.reworkContext}/>} {overrideApproval&&<HumanOverrideNotice approval={overrideApproval}/>} {gate&&<GateNotice gate={gate}/>} {item.codingEvidence&&["coding","code_review","testing","acceptance"].includes(viewStage)&&<CodingEvidence evidence={item.codingEvidence}/>} {latest?<Artifact artifact={latest}/>:<div className="empty compact"><Bot size={30}/><b>{isCurrentView?"等待 AI 执行":"该阶段暂无产物"}</b><span>{isCurrentView?"运行前可检查并排除发送上下文":"返回当前节点继续处理"}</span></div>}{viewStage==="coding"&&item.executions?.[0]&&<ExecutionResult execution={item.executions[0]}/>}</>}
  </section><aside className="action-panel"><h3>{isCurrentView?"下一步":"阶段记录"}</h3><p>{isCurrentView?(item.status==="awaiting_approval"?"检查 AI 结论、风险和证据后作出决定。":"确认上下文后手动启动本阶段 AI。"):`正在查看${stageLabels[viewStage]}的历史产物，不会改变当前流程。`}</p>
  {stageRun&&<button className="secondary wide view-run" onClick={()=>onViewRun(stageRun)}><RefreshCw size={16}/>查看{stageRun.status==="running"?"实时执行":"执行记录"}</button>}{isCurrentView&&item.stage!=="integration"&&(item.status==="awaiting_approval"?<button className="primary wide" onClick={onApprove}><ShieldCheck size={17}/>人工审批</button>:needsRequirementCorrection?<button className="primary wide" onClick={onEdit}><FileText size={17}/>纠正需求</button>:item.status!=="ai_running"&&<button className="primary wide" onClick={onRun}><Play size={17}/>{isRework?`启动${stageLabels[item.stage]}返工`:"启动 AI"}</button>)}
  {isCurrentView&&overrideView.visible&&<div className="override-action"><button className="secondary wide" onClick={onHumanOverride} disabled={overrideView.disabled}><ShieldCheck size={17}/>人工审核通过</button>{overrideView.disabled&&<small>{overrideView.reason}</small>} {!overrideView.disabled&&<small>通过后进入{overrideView.targetLabel}，人工意见将永久留痕。</small>}</div>}
  <ProjectAssociation item={item} onChanged={onProjectChanged}/><KnowledgeChanges changes={item.knowledgeChanges}/><dl><div><dt>优先级</dt><dd>{priority(item.priority)}</dd></div><div><dt>产物版本</dt><dd>{item.artifacts.length}</dd></div></dl></aside></div></div>}
function KnowledgeChanges({changes}:any){if(!changes)return null;const labels:any={candidate:"候选",published:"已发布",review:"待人工",conflict:"冲突"};return <details className="knowledge-changes"><summary><span>知识变更</span><b>{changes.candidates?.length||0}</b></summary><div className="knowledge-change-counts"><span>发布 {changes.publishedCount||0}</span><span>待审 {changes.reviewCount||0}</span><span>冲突 {changes.conflictCount||0}</span></div>{changes.candidates?.slice(0,12).map((item:any)=><article key={item.id||item.subjectKey}><b>{item.title}</b><span>{labels[item.status]||item.status} · {stageLabels[item.sourceStage as WorkflowStage]||item.sourceStage}</span><small>{item.content}</small></article>)}</details>}
function Artifact({artifact}:any){const c=artifact.content||{};return <div className="artifact"><div className="artifact-top"><div><span className="eyebrow">AI 结论 · v{artifact.version}</span><h3>{artifact.title}</h3></div>{typeof c.confidence==="number"&&<div className="confidence"><strong>{Math.round(c.confidence*100)}%</strong><span>置信度</span></div>}</div><p className="summary">{c.summary||"成果已生成，可展开结构化内容检查。"}</p><div className="artifact-metrics"><span><AlertTriangle size={15}/>{c.risks?.length||0} 项风险</span><span><Code2 size={15}/>{c.findings?.length||0} 项发现</span><span><FileText size={15}/>证据已记录</span></div>{artifact.stage==="prd"&&<ProductArtifactDetails content={c}/>}</div>}
function ProductArtifactDetails({content}:any){const view=productArtifactView(content);return <div className="product-artifact-details">{view.goal&&<section><b>真实业务目标</b><p>{view.goal}</p></section>}<section><b>AI 自主补全</b>{view.decisions.length?<ul>{view.decisions.map((x:any)=><li key={x.title}><strong>{x.title}</strong><span>{x.rationale}</span>{x.evidence.length>0&&<small>{x.evidence.join(" · ")}</small>}</li>)}</ul>:<p>本次没有额外产品决策</p>}</section><section><b>依据</b>{view.evidence.length?<ul>{view.evidence.map((x:any)=><li key={`${x.source}-${x.fact}`}><strong>{x.fact}</strong><small>{x.source}</small></li>)}</ul>:<p>未记录项目依据</p>}</section><section><b>采用的假设</b>{view.assumptions.length?<ul>{view.assumptions.map((x:any)=><li key={x.title}><strong>{x.title}</strong><span>{x.rationale}</span><small>验证：{x.validation||"后续评审"}</small></li>)}</ul>:<p>没有需要跟踪的假设</p>}</section><section className={view.blockers.length?"blocking":"clear"}><b>需要人工决定</b>{view.blockers.length?<ul>{view.blockers.map((x:any)=><li key={x.title}><strong>{x.title}</strong><span>{x.impact}</span><small>{x.options.join(" / ")}</small></li>)}</ul>:<p>没有需要人工补充的阻塞问题</p>}</section></div>}
function GateNotice({gate}:any){const reasons=gateReasons(gate);return <div className={`gate-notice ${gate.decision}`}><div><b>{gateLabel(gate.decision)}</b><span>AI 自动门禁</span></div>{reasons.length>0&&<ul>{reasons.map((reason:string)=><li key={reason}>{reason}</li>)}</ul>}</div>}
function HumanOverrideNotice({approval}:any){return <div className="human-override-notice"><div><b>人工例外通过</b><span>{new Date(approval.created_at).toLocaleString()}</span></div><p>{approval.comment}</p><small>当时累计打回 {approval.return_count||0} 次；AI 原始结论与风险保留。</small></div>}
function CodingEvidence({evidence}:any){const labels:any={valid:"有效",stale:"已过期",unverifiable:"无法验证",truncated:"已截断",missing:"缺失"};return <div className={`coding-evidence ${evidence.status}`}><div className="evidence-head"><div><span className="eyebrow">编码证据</span><h3>{labels[evidence.status]||"已记录"}</h3></div><code>{String(evidence.diffHash).slice(0,12)}</code></div><div className="evidence-meta"><span>{evidence.fileCount} 个文件</span><span>+{evidence.additions} / -{evidence.deletions}</span><span>{evidence.branch}</span></div><small>Execution {evidence.executionId}</small><details><summary>查看证据 Git diff</summary><pre>{evidence.diff||"没有文件差异"}</pre></details></div>}
function ReworkPanel({context}:any){const groups=groupReworkItems(context.items);return <div className="rework-panel"><div className="rework-head"><div><span className="eyebrow">为什么被打回</span><h3>{stageLabels[context.sourceStage as WorkflowStage]} → {stageLabels[context.targetStage as WorkflowStage]}</h3></div><span>{context.actorType==="ai_gate"?"AI 自动门禁":"人工审批"} · {new Date(context.decisionAt).toLocaleString()}</span></div>{context.unstructured&&<p className="rework-warning">缺少结构化评审结果，以下内容来自审批意见。</p>}{groups.map(group=><details className={`rework-group ${group.severity}`} open={group.severity==="S0"||group.severity==="S1"} key={group.severity}><summary><b>{group.severity}</b><span>{group.items.length} 项本轮返工需处理</span></summary>{group.items.map((item:any)=><article key={item.id}><h4>{item.title}</h4>{item.evidence&&<p><b>证据</b>{item.evidence}</p>}{item.impact&&<p><b>影响</b>{item.impact}</p>}{item.recommendation&&<p><b>建议</b>{item.recommendation}</p>}</article>)}</details>)}{context.risks?.length>0&&<details className="rework-extra"><summary>其他风险（{context.risks.length}）</summary><ul>{context.risks.map((risk:string)=><li key={risk}>{risk}</li>)}</ul></details>}{context.openQuestions?.length>0&&<details className="rework-extra"><summary>待确认问题（{context.openQuestions.length}）</summary><ul>{context.openQuestions.map((q:string)=><li key={q}>{q}</li>)}</ul></details>}</div>}

function NewRequirement({onClose,onDone}:any){const [f,setF]=useState({title:"",businessProblem:"",expectedOutcome:"",priority:"medium",projectId:""});const [projects,setProjects]=useState<any[]>([]);const [err,setErr]=useState("");useEffect(()=>{api<any[]>("/projects").then(setProjects)},[]);return <Modal title="新建需求" subtitle="保存后进入产品 AI 待启动状态" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await post("/requirements",{...f,projectId:f.projectId||undefined});onDone()}catch(x:any){setErr(x.message)}}}><Label text="关联项目"><select value={f.projectId} onChange={e=>setF({...f,projectId:e.target.value})}><option value="">暂不关联</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name} · {p.defaultBranch}</option>)}</select></Label><Label text="需求标题"><input value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="例如：统一订单备注校验"/></Label><Label text="业务背景与当前问题"><textarea value={f.businessProblem} onChange={e=>setF({...f,businessProblem:e.target.value})} placeholder="描述现状、用户和具体问题"/></Label><Label text="期望业务结果"><textarea value={f.expectedOutcome} onChange={e=>setF({...f,expectedOutcome:e.target.value})} placeholder="描述可观察的结果"/></Label><Label text="优先级"><select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="urgent">紧急</option></select></Label>{err&&<p className="form-error">{err}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary">保存需求</button></div></form></Modal>}

function EditRequirement({item,onClose,onDone}:{item:Detail,onClose:()=>void,onDone:()=>void}){const latest=item.artifacts[0]?.content;const [f,setF]=useState({title:item.title,businessProblem:item.businessProblem,expectedOutcome:item.expectedOutcome,priority:item.priority,clarifications:item.clarifications||"",changeSummary:"根据打回意见补充需求"});const [err,setErr]=useState("");return <Modal title="纠正需求" subtitle={`保存后生成 v${(item.version||1)+1}，旧版本和打回记录会保留`} onClose={onClose}>{latest?.openQuestions?.length>0&&<div className="clarification-questions"><b>AI 待确认问题</b><ul>{latest.openQuestions.slice(0,8).map((q:string)=><li key={q}>{q}</li>)}</ul></div>}<form onSubmit={async e=>{e.preventDefault();try{await patch(`/requirements/${item.id}`,f);onDone()}catch(x:any){setErr(x.message)}}}><Label text="需求标题"><input value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></Label><Label text="业务背景与当前问题"><textarea value={f.businessProblem} onChange={e=>setF({...f,businessProblem:e.target.value})}/></Label><Label text="期望业务结果与验收规则"><textarea value={f.expectedOutcome} onChange={e=>setF({...f,expectedOutcome:e.target.value})}/></Label><Label text="针对打回问题的澄清"><textarea value={f.clarifications} onChange={e=>setF({...f,clarifications:e.target.value})} placeholder="逐条回答 AI 的待确认问题，并写清规则、范围、异常和兼容策略"/></Label><Label text="本次修改说明"><input value={f.changeSummary} onChange={e=>setF({...f,changeSummary:e.target.value})}/></Label><Label text="优先级"><select value={f.priority} onChange={e=>setF({...f,priority:e.target.value as Detail["priority"]})}><option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="urgent">紧急</option></select></Label>{err&&<p className="form-error">{err}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary">保存 v{(item.version||1)+1}</button></div></form></Modal>}

function ProjectAssociation({item,onChanged}:{item:Detail,onChanged:()=>void}){const [projects,setProjects]=useState<any[]>([]),[saving,setSaving]=useState(false);useEffect(()=>{api<any[]>("/projects").then(setProjects)},[]);return <div className="project-association"><span>关联项目</span>{projects.length?<select aria-label="关联项目" value={item.projectId||""} disabled={saving} onChange={async e=>{setSaving(true);try{await patch(`/requirements/${item.id}/project`,{projectId:e.target.value||null});await onChanged()}finally{setSaving(false)}}}><option value="">未关联</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>:<small>请先在“项目”中登记仓库</small>}</div>}
function RunModal({item,busy,onClose,onRun}:{item:Detail,busy:boolean,onClose:()=>void,onRun:()=>void}){const coding=item.stage==="coding";return <Modal title={`启动 ${stageLabels[item.stage]} AI`} subtitle="确认后才会发送上下文并产生 API 调用" onClose={onClose}><div className="context-box"><div><b>模型</b><span>{coding?"OPENAI_CODING_MODEL":"OPENAI_MODEL"}（服务端配置）</span></div><div><b>发送内容</b><span>{coding?"需求、已批准产物和 AI 主动读取的相关源码":"需求字段、当前阶段、已批准产物"}</span></div><div><b>本地操作</b><span>{coding?"创建隔离 worktree、修改文件、运行白名单命令":"不修改项目源码"}</span></div><div><b>不会执行</b><span>自动提交、合并、推送；读取 .env、密钥和 Git 内部文件</span></div></div><div className="notice"><ShieldCheck size={18}/><span>{coding?"源码只写入隔离 worktree，完成后必须人工检查 Git diff。":"本次运行结果将保存为不可覆盖的新版本。"}</span></div><div className="modal-actions"><button className="secondary" onClick={onClose}>取消</button><button className="primary" onClick={onRun} disabled={busy}>{busy?<RefreshCw className="spin" size={17}/>:<Play size={17}/>}确认并运行</button></div></Modal>}

function ExecutionResult({execution}:any){const visibleEvents=(execution.events||[]).filter((event:any)=>event.type==="item.completed");return <div className="execution-result"><div className="execution-head"><div><span className="eyebrow">独立 Codex 编码会话</span><h3>{execution.branch}</h3></div><StatusPill ok={execution.status==="completed"} text={execution.status==="completed"?"执行完成":"需要检查"}/></div>{execution.codexThreadId&&<div className="codex-session"><span>会话 ID</span><code>{execution.codexThreadId}</code><small>继续执行：codex resume {execution.codexThreadId}</small></div>}<p className="execution-path">{execution.worktreePath}</p>{visibleEvents.length>0&&<div className="event-list">{visibleEvents.map((event:any,i:number)=><div key={`${event.item?.id||i}`}><b>{eventLabel(event.item?.type)}</b><span>{event.item?.text||event.item?.command||event.item?.status||"已完成"}</span></div>)}</div>} {execution.commands?.length>0&&<div className="command-list">{execution.commands.map((c:any,i:number)=><div key={i}><code>{c.command} {c.args.join(" ")}</code><b className={c.code===0?"ok":"failed"}>exit {c.code}</b></div>)}</div>}<details><summary>查看 Git diff</summary><pre>{execution.diff||"没有文件差异"}</pre></details></div>}
function StatusPill({ok,text}:{ok:boolean,text:string}){return <span className={`status ${ok?"ai_ready":"returned"}`}>{text}</span>}
function eventLabel(type:string|undefined){return ({agent_message:"Codex 总结",command_execution:"命令",file_change:"文件修改",reasoning:"分析"} as Record<string,string>)[type||""]||type||"事件"}
function ApprovalModal({item,onClose,onSubmit}:any){const [decision,setDecision]=useState("approve"),[comment,setComment]=useState("成果和证据已检查"),[condition,setCondition]=useState("");const target=stageLabels[returnStage(item.stage as WorkflowStage)];return <Modal title="人工审批" subtitle={`你的决定将进入永久审批记录；打回目标为${target}`} onClose={onClose}><div className="segments">{[["approve","批准"],["conditional","条件批准"],["return",`打回${target}`]].map(x=><button className={decision===x[0]?"selected":""} onClick={()=>setDecision(x[0])} key={x[0]}>{x[1]}</button>)}</div><Label text="审批意见"><textarea value={comment} onChange={e=>setComment(e.target.value)}/></Label>{decision==="conditional"&&<Label text="批准条件"><textarea value={condition} onChange={e=>setCondition(e.target.value)} placeholder="条件、负责人和截止时间"/></Label>}<div className="modal-actions"><button className="secondary" onClick={onClose}>取消</button><button className="primary" onClick={()=>onSubmit({decision,comment,condition:condition||undefined})}>提交决定</button></div></Modal>}
function HumanOverrideModal({item,onClose,onSubmit}:any){const [comment,setComment]=useState(""),[error,setError]=useState("");const artifact=item.artifacts.find((entry:any)=>entry.stage===item.stage);const content=artifact?.content||{};const view=humanOverrideView(item.stage,item.humanOverride);const submit=async()=>{if(!comment.trim()){setError("必须填写人工审核意见");return}try{await onSubmit(comment.trim())}catch(e:any){setError(e.message)}};return <Modal title="人工审核通过" subtitle={`这是一条例外放行记录，通过后进入${view.targetLabel}`} onClose={onClose}><div className="override-summary"><b>AI 当前结论</b><p>{content.summary||"当前成果没有摘要"}</p><span>本阶段已打回 {item.humanOverride?.returnCount||0} 次</span></div>{content.risks?.length>0&&<div className="override-list"><b>未解决风险</b><ul>{content.risks.map((risk:string)=><li key={risk}>{risk}</li>)}</ul></div>}{content.openQuestions?.length>0&&<div className="override-list"><b>待确认问题</b><ul>{content.openQuestions.map((question:string)=><li key={question}>{question}</li>)}</ul></div>}<Label text="人工审核意见（必填）"><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="说明已核查的证据、接受的风险和放行依据"/></Label>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={onClose}>取消</button><button className="primary" onClick={submit} disabled={!comment.trim()}>确认通过并进入{view.targetLabel}</button></div></Modal>}

function IntegrationPanel({item,current,onIntegrate,onRefresh}:any){
  const [check,setCheck]=useState<any>(null),[branches,setBranches]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
  useEffect(()=>{setError("");setCheck(null)},[item.status]);
  const loadCheck=async()=>{const response=await fetch(`/api/requirements/${item.id}/integration-check`);const data=await response.json();setCheck(data);if(!response.ok)setError(data.message||"预检未通过")};
  const load=async()=>{setLoading(true);setError("");try{await loadCheck()}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{if(!current||item.status!=="awaiting_merge")return;let active=true;(async()=>{setLoading(true);setError("");try{const data=await api<any>(`/requirements/${item.id}/integration-branches`);if(!active)return;setBranches(data);if(!item.integrationTargetBranch&&data.selectedTarget){await patch(`/requirements/${item.id}/integration-target`,{branch:data.selectedTarget});await onRefresh();}await loadCheck()}catch(e:any){if(active)setError(e.message)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[item.id,item.status,item.integrationTargetBranch,current]);
  const target=item.integrationTargetBranch||branches?.selectedTarget||item.integrationRun?.targetBranch||"";
  const view=integrationView(item.status,check,item.integrationRun,target),displayLabel=!current&&!item.integrationRun?"尚未进入":view.label,verificationPlan=check?.plannedCommands?.length?check:item.integrationRun?.preflight;
  const selectTarget=async(branch:string)=>{setLoading(true);setError("");setCheck(null);try{await patch(`/requirements/${item.id}/integration-target`,{branch});setBranches((value:any)=>({...value,selectedTarget:branch}));await onRefresh()}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  const rerun=async()=>{setLoading(true);try{await post(`/requirements/${item.id}/integration-test`,{});await onRefresh()}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  return <div className="integration-panel"><div className="integration-head"><div><span className="eyebrow">本地改动应用</span><h3>{displayLabel}</h3></div><span className={`status ${current?item.status:""}`}>{current?(statusLabels[item.status as WorkflowStatus]||view.label):"历史阶段"}</span></div><div className="integration-route"><div><span>源 worktree 分支</span><code>{item.codingEvidence?.branch||item.integrationRun?.sourceBranch||"-"}</code><small>{item.codingEvidence?.worktreePath||item.integrationRun?.worktreePath||"-"}</small></div><ChevronRight/><div><span>本地目标分支</span>{current&&branches?.branches?.length?<select aria-label="目标分支" value={target} disabled={loading} onChange={e=>selectTarget(e.target.value)}>{branches.branches.map((branch:any)=><option value={branch.name} key={branch.name}>{branch.name}{branch.current?"（当前）":""}{branch.protected?"（保护）":""}</option>)}</select>:<code>{target||"尚未选择"}</code>}<small>{branches?.currentBranch?`仓库当前分支：${branches.currentBranch}`:item.projectName||"未关联项目"}</small></div></div><div className="no-push"><ShieldCheck size={17}/><span>{view.safetyLabel}</span></div>{verificationPlan?.plannedCommands?.length>0&&<div className="verification-plan"><div><b>自动识别模块</b><span>{verificationPlan.changedModules?.join("、")||"项目根目录"}</span></div>{verificationPlan.plannedCommands.map((command:any,index:number)=><code key={index}>{command.command} {(command.argsPrefix||[]).join(" ")}</code>)}</div>}{check?.checks?.length>0&&<div className="integration-checks">{check.checks.map((entry:any)=><div className={entry.ok?"ok":"failed"} key={entry.id}><b>{entry.ok?"通过":"未通过"}</b><span>{entry.label}<small>{entry.detail}</small></span></div>)}</div>}{error&&<p className="integration-error">{error}</p>}{item.integrationRun&&<IntegrationRunResult run={item.integrationRun}/>} {current&&(view.showRecheck||view.showIntegrate||view.showRerun)&&<div className="integration-actions">{view.showRecheck&&<button className="secondary" onClick={load} disabled={loading}><RefreshCw className={loading?"spin":""} size={16}/>重新检查</button>}{view.showIntegrate&&<button className="primary" onClick={onIntegrate} disabled={!view.canIntegrate||loading} title={view.disabledReasons.join("；")}><Check size={16}/>{view.actionLabel}</button>}{view.showRerun&&<button className="primary" onClick={rerun} disabled={loading}><TestTube2 size={16}/>重新运行应用后测试</button>}</div>}{current&&view.showIntegrate&&!view.canIntegrate&&view.disabledReasons.length>0&&<ul className="integration-disabled-reasons">{view.disabledReasons.map((reason:string)=><li key={reason}>{reason}</li>)}</ul>}</div>}
function IntegrationRunResult({run}:any){const worktreeMode=run.preflight?.applicationMode==="worktree",conflictFiles=run.preflight?.conflictFiles||[];return <div className={`integration-result ${run.status}`}><b>最近本地应用：{run.status}</b>{run.sourceCommit&&<p>源 worktree 提交 <code>{run.sourceCommit}</code></p>}{run.targetCommit&&<p>{worktreeMode?"应用前目标提交":"目标提交"} <code>{run.targetCommit}</code></p>}{run.status==="conflict"&&<div className="integration-conflicts"><b>与目标分支存在冲突，目标工作树已恢复</b>{conflictFiles.length>0&&<ul>{conflictFiles.map((file:string)=><li key={file}><code>{file}</code></li>)}</ul>}</div>}{worktreeMode&&run.status!=="conflict"&&<p>改动保留在本地暂存区。检查后由你手动执行 <code>git commit</code>。</p>}{run.error&&<details><summary>查看 Git 错误</summary><pre>{run.error}</pre></details>}{run.commandResults?.map((result:any,index:number)=><details key={index}><summary><code>{result.command} {(result.args||[]).join(" ")}</code> · exit {result.code}</summary><pre>{result.stdout||result.stderr||"没有输出"}</pre></details>)}</div>}
function IntegrationConfirm({item,busy,onClose,onSubmit}:any){const target=item.integrationTargetBranch||"",[confirmation,setConfirmation]=useState("");const view=integrationView(item.status,{allowed:true},item.integrationRun,target,confirmation);return <Modal title="应用到本地工作区" subtitle="worktree 改动将进入目标分支暂存区，不会创建提交" onClose={onClose}><div className="context-box"><div><b>需求</b><span>{item.code} · {item.title}</span></div><div><b>源 worktree</b><span>{item.codingEvidence?.branch||"AI 独立分支"}</span></div><div><b>本地目标分支</b><span>{target||"尚未选择"}</span></div><div><b>提交与远端</b><span>不会 commit，不会 push，不会创建 PR</span></div></div>{view.protectedTarget&&<div className="protected-confirm"><div className="notice"><AlertTriangle size={18}/><span><b>{target}</b> 是保护分支。请输入完整分支名确认。</span></div><Label text={`输入 ${target}`}><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></Label></div>}<div className="notice"><AlertTriangle size={18}/><span>应用后会运行测试；无论测试是否通过，改动都保留在本地暂存区，等待你检查并手动提交。</span></div><div className="modal-actions"><button className="secondary" onClick={onClose}>取消</button><button className="primary" onClick={()=>onSubmit(confirmation)} disabled={busy||!view.confirmationValid||!target}>{busy?<RefreshCw className="spin" size={17}/>:<Check size={17}/>}确认应用到本地</button></div></Modal>}

function Projects(){const [projects,setProjects]=useState<any[]>([]);const [f,setF]=useState({name:"Soto Dine",repoPath:"/Users/whp/Documents/workspace/haini-workspace/soto-dine",defaultBranch:"prod",allowedCommands:[{command:"mvn",argsPrefix:["test","-pl","dine-service/dine-product-service"]}],sensitivePatterns:[".env","*.pem","*.key"]});useEffect(()=>{api<any[]>("/projects").then(setProjects)},[]);return <div className="content"><section className="section"><div className="section-head"><div><h2>本地项目</h2><p>项目知识库会被产品、研发、Review 和测试 AI 共同使用</p></div></div>{projects.map(p=><ProjectRow project={p} key={p.id}/>)}{!projects.length&&<div className="project-form"><Label text="项目名称"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Label><Label text="仓库路径"><input value={f.repoPath} onChange={e=>setF({...f,repoPath:e.target.value})}/></Label><Label text="默认分支"><input value={f.defaultBranch} onChange={e=>setF({...f,defaultBranch:e.target.value})}/></Label><button className="primary" onClick={async()=>{await post("/projects",f);setProjects(await api("/projects"))}}><FolderGit2 size={17}/>登记项目</button></div>}</section></div>}
function ProjectRow({project}:any){
  const [knowledge,setKnowledge]=useState<any>(null),[memory,setMemory]=useState<any>(null),[busy,setBusy]=useState(false);
  const load=()=>Promise.all([
    api(`/projects/${project.id}/knowledge`).then(setKnowledge),
    api(`/projects/${project.id}/memory`).then(setMemory),
  ]);
  useEffect(()=>{
    load();
    if(knowledge?.status!=="building")return;
    const timer=setInterval(load,1000);
    return()=>clearInterval(timer);
  },[project.id,knowledge?.status]);
  const view=projectKnowledgeView(knowledge);
  const layerLabels:any={source_fact:"源码事实",project_rule:"项目规则",decision:"决策",requirement_experience:"需求经验"};
  return <div className="project-block">
    <div className="project-row"><FolderGit2/><div><b>{project.name}</b><span>{project.repoPath} · {project.defaultBranch}</span></div><Check/></div>
    <div className="knowledge-status">
      <div><span>源码知识库</span><b>{view.label} · {view.version}</b><small>HEAD {String(view.head).slice(0,12)} · {view.entryCount} 条知识 · {view.moduleCount} 个模块</small>{view.error&&<em>{view.error}</em>}</div>
      <button className="secondary" disabled={!view.canRebuild||busy} onClick={async()=>{setBusy(true);try{await post(`/projects/${project.id}/knowledge/rebuild`,{});await load()}finally{setBusy(false)}}}><RefreshCw className={view.label==="生成中"?"spin":""} size={15}/>重建知识库</button>
    </div>
    {memory&&<details className="project-memory">
      <summary><b>项目持续记忆</b><span>{memory.total} 条正式知识</span></summary>
      <div className="memory-layers">
        {Object.entries(memory.layers||{}).map(([layer,count]:any)=><span key={layer}>{layerLabels[layer]||layer}<b>{count}</b></span>)}
      </div>
      {(memory.records||[]).slice(0,20).map((record:any)=><article key={record.id}>
        <div><b>{record.title}</b><span>{layerLabels[record.layer]||record.layer} · v{record.version}</span></div>
        <p>{record.content}</p>
        <small>{record.sourceStage} · {record.riskLevel==="high"?"高风险":"已验证"}</small>
      </article>)}
    </details>}
  </div>;
}
function SettingsPage(){const [config,setConfig]=useState<GateConfig|null>(null),[saving,setSaving]=useState(false),[saved,setSaved]=useState("");useEffect(()=>{api<GateConfig>("/settings/gates").then(setConfig)},[]);const save=async(next:GateConfig)=>{setConfig(next);setSaving(true);setSaved("");try{setConfig(await patch<GateConfig>("/settings/gates",next));setSaved("已保存")}finally{setSaving(false)}};return <div className="content"><section className="section settings"><h2>本机设置</h2><div className="setting-row"><Bot/><div><b>OpenAI API</b><span>密钥从 OPENAI_API_KEY 环境变量读取</span></div><span className="status ai_ready">服务端检查</span></div><div className="setting-row"><ShieldCheck/><div><b>隐私与执行</b><span>仅监听 127.0.0.1，命令清单外需确认</span></div></div><div className="setting-row"><TestTube2/><div><b>数据目录</b><span>SQLite、附件和运行日志保存在本机 data/</span></div></div></section><section className="section gate-settings"><div className="section-head"><div><h2>AI 自动门禁</h2><p>清晰低风险的阶段自动推进，异常才需要人工</p></div>{saved&&<span className="status ai_ready">{saved}</span>}</div>{config?<><label className="gate-setting-row"><div><b>自动流转</b><span>关闭后所有阶段都等待人工审批</span></div><input type="checkbox" checked={config.autoTransitionEnabled} disabled={saving} onChange={e=>save({...config,autoTransitionEnabled:e.target.checked})}/></label><label className="gate-setting-row"><div><b>最低置信度</b><span>低于阈值时转人工审核</span></div><input aria-label="最低置信度" type="number" min="0" max="1" step="0.05" value={config.confidenceThreshold} disabled={saving} onChange={e=>setConfig({...config,confidenceThreshold:Number(e.target.value)})} onBlur={()=>save(config)}/></label><div className="mandatory-stages"><b>强制人工阶段</b><span>编码自测与运营验收默认不可自动通过</span><div>{workflowStages.map(stage=><label key={stage}><input type="checkbox" checked={config.mandatoryHumanStages.includes(stage)} disabled={saving} onChange={e=>{const stages=e.target.checked?[...config.mandatoryHumanStages,stage]:config.mandatoryHumanStages.filter(item=>item!==stage);save({...config,mandatoryHumanStages:stages})}}/>{stageLabels[stage]}</label>)}</div></div></>:<div className="empty compact">正在读取门禁配置</div>}</section></div>}
function RunDetailsModal({initialRun,onClose,onTerminal}:{initialRun:StageRun,onClose:()=>void,onTerminal:()=>Promise<void>}){const [run,setRun]=useState(initialRun),[events,setEvents]=useState(initialRun.events||[]),[tab,setTab]=useState<"process"|"input"|"raw"|"result">("process"),[error,setError]=useState("");useEffect(()=>{let source:EventSource|undefined;let closed=false;api<StageRun>(`/runs/${initialRun.id}`).then(snapshot=>{if(closed)return;setRun(snapshot);setEvents(snapshot.events||[]);if(!isTerminalRun(snapshot.status)){const after=(snapshot.events||[]).at(-1)?.sequence||0;source=new EventSource(`/api/runs/${snapshot.id}/events?after=${after}`);source.addEventListener("run-event",(message)=>{const event=JSON.parse((message as MessageEvent).data);setEvents(current=>mergeRunEvents(current,[event]));if(["run.completed","run.failed","run.interrupted"].includes(event.type)){source?.close();api<StageRun>(`/runs/${snapshot.id}`).then(setRun);onTerminal().catch(()=>{})}});source.onerror=()=>setError("实时连接暂时中断，正在自动重连");}}).catch(e=>setError(e.message));return()=>{closed=true;source?.close()}},[initialRun.id]);const raw=events.filter(event=>event.type==="output.delta"||event.type==="codex.event"||event.type==="diagnostic").map(event=>event.payload?.text||event.payload).map(value=>typeof value==="string"?value:JSON.stringify(value,null,2)).join("");return <div className="modal-backdrop"><div className="modal run-modal"><div className="modal-head"><div><h2>{stageLabels[run.stage]} · 执行详情</h2><p>真实输入、处理事件与输出均保存在本机</p></div><button className="icon-btn" onClick={onClose} title="关闭"><X size={19}/></button></div><div className="run-meta"><span>状态 <b>{run.status}</b></span><span>模型 <b>{run.model||"-"}</b></span><span>开始 <b>{new Date(run.createdAt).toLocaleString()}</b></span><span>事件 <b>{events.length}</b></span></div><div className="run-tabs">{[["process","执行过程"],["input","输入上下文"],["raw","原始输出"],["result","最终结果"]].map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key as any)}>{label}</button>)}</div><div className="run-panel">{error&&<div className="run-error">{error}</div>}{tab==="process"?(events.length?<div className="run-events">{displayRunEvents(events).map(event=><div className="run-event" key={event.sequence}><time>{event.createdAt?new Date(event.createdAt).toLocaleTimeString():`#${event.sequence}`}</time><b>{runEventLabel(event.type)}</b><pre>{JSON.stringify(event.payload,null,2)}</pre></div>)}</div>:<div className="run-empty">等待执行事件</div>):tab==="input"?<pre className="run-json">{JSON.stringify(run.input,null,2)}</pre>:tab==="raw"?<pre className="run-json">{raw||"尚未收到模型输出"}</pre>:<>{run.error&&<div className="run-error">{run.error}</div>}<pre className="run-json">{JSON.stringify(run.output,null,2)}</pre></>}</div></div></div>}
function Modal({title,subtitle,onClose,children}:any){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="icon-btn" onClick={onClose} title="关闭"><X size={19}/></button></div>{children}</div></div>}
function Label({text,children}:any){return <label><span>{text}</span>{children}</label>}
function priority(p:string){return ({low:"低",medium:"中",high:"高",urgent:"紧急"} as any)[p]||p}
function pageTitle(p:Page){return p==="dashboard"?"工作台":p==="projects"?"项目配置":p==="settings"?"设置":"全部需求"}
function pageSubtitle(p:Page){return p==="dashboard"?"聚焦需要你处理的工作":p==="projects"?"管理本地仓库与允许命令":p==="settings"?"模型、数据与安全配置":"查看所有研发工作流"}

createRoot(document.getElementById("root")!).render(<App/>);
