import React, { useEffect, useReducer, useRef, useState } from "react";
import { AlertTriangle, ChevronDown, ChevronUp, Plus, RefreshCw, Trash2 } from "lucide-react";
import type { WorkflowStage } from "@ai-workflow/shared";
import { ApiError, api } from "./api.js";
import { AccessibleDialog } from "./accessible-dialog.js";

export type Association = { id?: string; projectId: string; projectName?: string; role: "primary" | "collaborator"; usage: "context" | "delivery"; deliveryRequired: boolean; moduleMode: "auto" | "all" | "selected"; moduleIds: string[]; position: number; status?: "active" | "archived"; projectStatus?: "active" | "archived" };
export type ProjectChoice = { id: string; name: string; status: "active" | "archived"; modules?: Array<{ id?: string; name?: string; path?: string }> };
type ModuleState = Record<string, { status: "loading" | "ready" | "error"; modules: string[]; error?: string }>;
type RowErrors = Record<number, Partial<Record<keyof Association, string>>>;

export const activeAssociations = (items: Association[]) => items.filter(item => item.status !== "archived" && item.projectStatus !== "archived").sort((a, b) => a.position - b.position);
export const historyAssociations = (items: Association[]) => items.filter(item => item.status === "archived" || item.projectStatus === "archived");
export function moveAssociation(items: Association[], projectId: string, delta: -1 | 1) { const current = activeAssociations(items), index = current.findIndex(item => item.projectId === projectId), target = index + delta; if (index < 0 || target < 0 || target >= current.length) return items; [current[index], current[target]] = [current[target]!, current[index]!]; return [...current.map((item, position) => ({ ...item, position })), ...historyAssociations(items)]; }
export function requirementProjectsPayload(items: Association[]) { return activeAssociations(items).map(({ projectId, role, usage, deliveryRequired, moduleMode, moduleIds }, position) => ({ projectId, role, usage, deliveryRequired, moduleMode, moduleIds, position })); }
export function selectedModuleProjectIds(items: Association[]) { return [...new Set(activeAssociations(items).filter(item => item.moduleMode === "selected").map(item => item.projectId))]; }
export function shouldRequestModules(modules: ModuleState, projectId: string) { return !modules[projectId] || modules[projectId]?.status === "error"; }
export async function saveAssociationThenRefresh(put: () => Promise<unknown>, onClose: () => void, onSaved: () => Promise<void>, onRefreshError: (error: unknown) => void) { await put(); onClose(); try { await onSaved(); } catch (error) { onRefreshError(error); } }
const active = activeAssociations;
export function associationSummary(items: Association[]) { const current = active(items), primary = current.find(item => item.role === "primary"); return { primaryName: primary?.projectName || "未设置", primaryUsage: primary?.usage, deliveryCount: current.filter(item => item.usage === "delivery").length, requiredDeliveryCount: current.filter(item => item.usage === "delivery" && item.deliveryRequired).length, archivedCount: items.length - current.length, frozen: false }; }
export function phaseOneDeliveryGate(items: Association[]) { const count = active(items).filter(item => item.usage === "delivery").length; return count === 0 ? { kind: "missing" as const, message: "请先关联一个交付项目" } : count === 1 ? { kind: "ready" as const, message: "" } : { kind: "phase2" as const, message: "多项目编码将在第二期启用；当前可继续完善总体技术设计" }; }
export function availableProjectChoices(projects: ProjectChoice[], items: Association[]) { const used = new Set(items.map(item => item.projectId)); return projects.filter(project => project.status === "active" && !used.has(project.id)); }
export function setPrimary(items: Association[], projectId: string) { return items.map(item => item.status === "archived" || item.projectStatus === "archived" ? item : { ...item, role: item.projectId === projectId ? "primary" as const : "collaborator" as const }); }
export function setUsage(items: Association[], projectId: string, usage: Association["usage"]) { return items.map(item => item.projectId === projectId ? { ...item, usage, deliveryRequired: usage === "context" ? false : item.deliveryRequired } : item); }
const material = (items: Association[]) => active(items).map(({ projectId, role, usage, deliveryRequired, moduleMode, moduleIds }) => ({ projectId, role, usage, deliveryRequired, moduleMode, moduleIds: [...moduleIds].sort() })).sort((a, b) => a.projectId.localeCompare(b.projectId));
export function hasMaterialAssociationEdit(before: Association[], after: Association[], stage: WorkflowStage, snapshot: unknown) { return Boolean(snapshot) && ["technical_design", "coding", "code_review", "testing", "acceptance", "integration"].includes(stage) && JSON.stringify(material(before)) !== JSON.stringify(material(after)); }
export function validateAssociations(items: Association[], modules: ModuleState) { const rows: RowErrors = {}, current = active(items); const primaryCount = current.filter(item => item.role === "primary").length, seen = new Set<string>(); current.forEach((item, index) => { const error: Partial<Record<keyof Association, string>> = {}; if (primaryCount !== 1) error.role = "必须且只能设置一个主项目"; if (seen.has(item.projectId)) error.projectId = "项目不能重复"; seen.add(item.projectId); if (item.usage === "context" && item.deliveryRequired) error.deliveryRequired = "上下文项目不能要求交付"; if (item.moduleMode === "selected") { const state = modules[item.projectId]; if (!item.moduleIds.length) error.moduleIds = "请至少选择一个模块"; else if (!state || state.status !== "ready") error.moduleIds = "模块索引不可用，无法保存所选模块"; else if (item.moduleIds.some(id => !state.modules.includes(id))) error.moduleIds = "所选模块已不可用，请重新选择"; } if (Object.keys(error).length) rows[index] = error; }); return { valid: current.length > 0 && !Object.keys(rows).length, rows, general: current.length ? "" : "至少关联一个项目" }; }
export function associationApiErrors(error: unknown): { rows: RowErrors; general: string } { if (error instanceof ApiError) { const issues = (error.details as any)?.issues; if (Array.isArray(issues)) { const rows: RowErrors = {}; for (const issue of issues) { const [row, field] = issue.path || []; if (typeof row === "number" && typeof field === "string") rows[row] = { ...rows[row], [field]: issue.message }; } if (Object.keys(rows).length) return { rows, general: "" }; } return { rows: {}, general: error.message }; } return { rows: {}, general: error instanceof Error ? error.message : "保存关联项目失败" }; }
export type AssociationState = { items: Association[]; busy: boolean; requestId: number | null; error: string };
export function initialAssociationState(items: Association[]): AssociationState { return { items, busy: false, requestId: null, error: "" }; }
export function associationReducer(state: AssociationState, action: { type: "change"; items: Association[] } | { type: "submit"; requestId: number } | { type: "failure" | "success"; requestId: number; error?: string }): AssociationState { if (action.type === "change") return { ...state, items: action.items, error: "" }; if (action.type === "submit") return state.busy ? state : { ...state, busy: true, requestId: action.requestId, error: "" }; if (state.requestId !== action.requestId) return state; return { ...state, busy: false, requestId: null, error: action.type === "failure" ? action.error || "保存失败" : "" }; }

export function PlannedDelivery({ items, stage }: { items: Association[]; stage: WorkflowStage }) { if (!["technical_design", "coding"].includes(stage)) return null; const deliveries = active(items).filter(item => item.usage === "delivery"); return <div className="planned-delivery"><b>计划交付</b>{deliveries.length ? deliveries.map(item => <div key={item.projectId}><span>{item.projectName}</span><small>{moduleLabel(item)} · 第二期启用分项目执行</small></div>) : <small>请先关联交付项目</small>}</div>; }
export function RequirementProjectSummary({ items, snapshot, onManage }: { items: Association[]; snapshot?: any; onManage: () => void }) { const summary = associationSummary(items), primary = active(items).find(item => item.role === "primary"); return <div className="project-association"><span>关联项目</span><b>{summary.primaryName}</b><small>{primary?.usage === "context" ? "主项目 · 仅上下文" : "主项目 · 参与交付"} · {summary.deliveryCount} 个交付项目 · {summary.requiredDeliveryCount} 个必需</small><small>{primary ? moduleLabel(primary) : "未设置模块范围"} · {snapshot ? `已冻结 v${snapshot.version}` : "尚未冻结"}</small><button className="secondary wide" onClick={onManage}>管理关联项目</button></div>; }

export function RequirementProjectsDialog({ requirementId, stage, onClose, onSaved, onRefreshError }: { requirementId: string; stage: WorkflowStage; onClose: () => void; onSaved: () => Promise<void>; onRefreshError: (error: unknown) => void }) {
  const [projects, setProjects] = useState<ProjectChoice[]>([]), [snapshot, setSnapshot] = useState<any>(null), [baseline, setBaseline] = useState<Association[]>([]), [state, dispatch] = useReducer(associationReducer, initialAssociationState([])), [modules, setModules] = useState<ModuleState>({}), [addProjectId, setAddProjectId] = useState(""), [errors, setErrors] = useState<{ rows: RowErrors; general: string }>({ rows: {}, general: "" }); const request = useRef(0), moduleGeneration = useRef(0), modulesRef = useRef<ModuleState>({}), itemsRef = useRef<Association[]>([]), moduleInFlight = useRef(new Set<string>());
  const requestModules = (projectId: string) => { if (!shouldRequestModules(modulesRef.current, projectId) || moduleInFlight.current.has(projectId)) return; const generation = moduleGeneration.current; moduleInFlight.current.add(projectId); const loading = { status: "loading" as const, modules: [] }; modulesRef.current = { ...modulesRef.current, [projectId]: loading }; setModules(modulesRef.current); api<{ modules: Array<{ id: string; path: string }> }>(`/projects/${projectId}/modules`).then(value => { if (generation !== moduleGeneration.current || !selectedModuleProjectIds(itemsRef.current).includes(projectId)) return; const ready = { status: "ready" as const, modules: [...new Set(value.modules.flatMap(module => [module.id, module.path]).filter(Boolean))] }; modulesRef.current = { ...modulesRef.current, [projectId]: ready }; setModules(modulesRef.current); }, error => { if (generation !== moduleGeneration.current || !selectedModuleProjectIds(itemsRef.current).includes(projectId)) return; const failed = { status: "error" as const, modules: [], error: error instanceof Error ? error.message : "模块加载失败" }; modulesRef.current = { ...modulesRef.current, [projectId]: failed }; setModules(modulesRef.current); }).finally(() => { moduleInFlight.current.delete(projectId); if (modulesRef.current[projectId]?.status === "loading" && !selectedModuleProjectIds(itemsRef.current).includes(projectId)) { const next = { ...modulesRef.current }; delete next[projectId]; modulesRef.current = next; } }); };
  const choices = availableProjectChoices(projects, state.items), current = active(state.items), materialWarning = hasMaterialAssociationEdit(baseline, state.items, stage, snapshot);
  useEffect(() => { let live = true; const generation = ++moduleGeneration.current; Promise.all([api<ProjectChoice[]>("/projects?status=all"), api<any>(`/requirements/${requirementId}/projects`)]).then(([all, detail]) => { if (!live || generation !== moduleGeneration.current) return; setProjects(all); setSnapshot(detail.snapshot); setBaseline(detail.projects); itemsRef.current = detail.projects; dispatch({ type: "change", items: detail.projects }); selectedModuleProjectIds(detail.projects).forEach(requestModules); }, error => { if (live) setErrors({ rows: {}, general: error.message }); }); return () => { live = false; moduleGeneration.current += 1; }; }, [requirementId]);
  const add = () => { const project = choices.find(choice => choice.id === addProjectId); if (project) { change([...current, { projectId: project.id, projectName: project.name, role: current.length ? "collaborator" : "primary", usage: "context", deliveryRequired: false, moduleMode: "auto", moduleIds: [], position: current.length, status: "active", projectStatus: "active" }, ...historyAssociations(state.items)]); setAddProjectId(""); } };
  const change = (items: Association[]) => { const editable = activeAssociations(items).map((item, position) => ({ ...item, position })); const next = [...editable, ...historyAssociations(items)]; itemsRef.current = next; dispatch({ type: "change", items: next }); setErrors({ rows: {}, general: "" }); };
  const update = (index: number, patch: Partial<Association>) => { let items = state.items.map((item, i) => i === index ? { ...item, ...patch } : item); if (patch.role === "primary") items = setPrimary(items, state.items[index]!.projectId); if (patch.usage) items = setUsage(items, state.items[index]!.projectId, patch.usage); if (patch.moduleMode && patch.moduleMode !== "selected") items = items.map((item, i) => i === index ? { ...item, moduleIds: [] } : item); change(items); if (patch.moduleMode === "selected") requestModules(state.items[index]!.projectId); };
  const save = async () => { if (state.busy) return; const validation = validateAssociations(state.items, modules); if (!validation.valid) { setErrors({ rows: validation.rows, general: validation.general }); return; } if (materialWarning && !window.confirm("此修改将使已批准的技术设计失效，并返回技术设计阶段。确认继续吗？")) return; const requestId = ++request.current; dispatch({ type: "submit", requestId }); try { await saveAssociationThenRefresh(() => api(`/requirements/${requirementId}/projects`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(requirementProjectsPayload(state.items)) }), onClose, onSaved, onRefreshError); dispatch({ type: "success", requestId }); } catch (error) { const mapped = associationApiErrors(error); setErrors(mapped); dispatch({ type: "failure", requestId, error: mapped.general }); } };
  return <AccessibleDialog className="association-editor" title="管理关联项目" subtitle="配置需求上下文、交付责任和模块范围" titleId="association-editor-title" busy={state.busy} onClose={onClose}><div className="association-rows">{current.map((item, index) => <AssociationRow key={item.projectId} item={item} index={index} count={current.length} modules={modules[item.projectId]} errors={errors.rows[index]} busy={state.busy} onUpdate={(patch: Partial<Association>) => update(state.items.findIndex(row => row.projectId === item.projectId), patch)} onMove={(delta: -1 | 1) => change(moveAssociation(state.items, item.projectId, delta))} onRemove={() => change(state.items.filter(row => row.projectId !== item.projectId))}/>)}</div><div className="association-add"><label><span>添加协作项目</span><select aria-label="添加协作项目" value={addProjectId} disabled={state.busy || !choices.length} onChange={event => setAddProjectId(event.target.value)}><option value="">选择项目</option>{choices.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><button type="button" className="secondary" onClick={add} disabled={state.busy || !addProjectId}><Plus size={16}/>添加</button></div>{historyAssociations(state.items).length > 0 && <section className="association-history" aria-label="历史关联"><b>历史关联</b>{historyAssociations(state.items).map(item => <div className="association-row archived" key={item.projectId}><b>{item.projectName}</b><span>项目已归档 · 只读保留</span></div>)}</section>}{materialWarning && <div className="association-warning"><AlertTriangle size={16}/>保存后已批准技术设计将失效，流程返回技术设计阶段。</div>}{errors.general && <p className="form-error" role="alert">{errors.general}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={state.busy} onClick={onClose}>取消</button><button type="button" className="primary" disabled={state.busy} onClick={save}>{state.busy && <RefreshCw className="spin" size={16}/>}保存关联</button></div></AccessibleDialog>;
}

function AssociationRow({ item, index, count, modules, errors = {}, busy, onUpdate, onMove, onRemove }: any) { return <fieldset className="association-row" disabled={busy}><legend>关联项目 {index + 1}</legend><div className="association-row-head"><b>{item.projectName}</b><label className="radio-label"><input type="radio" name="primary-project" checked={item.role === "primary"} onChange={() => onUpdate({ role: "primary" })}/>主项目</label><div className="association-row-actions"><button type="button" className="icon-btn" title="上移" aria-label={`上移 ${item.projectName}`} disabled={index === 0} onClick={() => onMove(-1)}><ChevronUp size={16}/></button><button type="button" className="icon-btn" title="下移" aria-label={`下移 ${item.projectName}`} disabled={index === count - 1} onClick={() => onMove(1)}><ChevronDown size={16}/></button><button type="button" className="icon-btn" title="移除关联" aria-label={`移除 ${item.projectName}`} onClick={onRemove}><Trash2 size={16}/></button></div></div><div className="association-controls"><fieldset className="usage-segments"><legend>用途</legend><div role="group" aria-label={`${item.projectName} 用途`}><button type="button" aria-pressed={item.usage === "context"} className={item.usage === "context" ? "selected" : ""} onClick={() => onUpdate({ usage: "context" })}>上下文</button><button type="button" aria-pressed={item.usage === "delivery"} className={item.usage === "delivery" ? "selected" : ""} onClick={() => onUpdate({ usage: "delivery" })}>交付</button></div></fieldset><label><span>模块范围</span><select value={item.moduleMode} onChange={event => onUpdate({ moduleMode: event.target.value })}><option value="auto">自动</option><option value="all">全部</option><option value="selected">指定模块</option></select></label><label className="check-label"><input type="checkbox" disabled={item.usage !== "delivery"} checked={item.deliveryRequired} onChange={event => onUpdate({ deliveryRequired: event.target.checked })}/>必须交付</label></div>{item.moduleMode === "selected" && <label><span>选择模块</span>{modules?.status === "loading" ? <small>正在加载模块…</small> : modules?.status === "error" ? <small className="field-error">模块加载失败：{modules.error}</small> : modules?.modules.length ? <select multiple aria-label={`${item.projectName} 模块`} value={item.moduleIds} onChange={event => onUpdate({ moduleIds: Array.from(event.target.selectedOptions, (option: any) => option.value) })}>{modules.modules.map((module: string) => <option value={module} key={module}>{module}</option>)}</select> : <small className="field-error">没有可用模块，无法保存指定模块范围</small>}</label>}{Object.values(errors).map((message: any, i) => <small className="field-error" role="alert" key={i}>{message}</small>)}</fieldset>; }
function moduleLabel(item: Association) { return item.moduleMode === "auto" ? "模块自动匹配" : item.moduleMode === "all" ? "全部模块" : `指定 ${item.moduleIds.length} 个模块`; }
